// Generated by Wrangler by running `wrangler types`

interface Env {
  EMAIL_TO_RSS_KV: KVNamespace;
  EMAIL_TO_RSS_DB: D1Database;
  OPENAI_API_KEY: string;
  AUTH_USERNAME: string;
  AUTH_PASSWORD: string;
}
